const DEFAULT_COLOR = '#000000';
const DEFAULT_BACKGROUND = '#ffffff';
const DEFAULT_OFFSET_BACKGROUND = '#255d83';
const DEFAULT_OFFSET_COLOR = '#ffffff';
const DEFAULT_PADDING = '2em 2em 2em 2em';

export default {
  DEFAULT_OFFSET_COLOR: DEFAULT_OFFSET_COLOR,
  DEFAULT_OFFSET_BACKGROUND: DEFAULT_OFFSET_BACKGROUND,
  DEFAULT_BACKGROUND: DEFAULT_BACKGROUND,
  DEFAULT_COLOR: DEFAULT_COLOR,
  DEFAULT_PADDING: DEFAULT_PADDING
}